import { tool } from "@opencode-ai/plugin";
import * as fs from "fs";
import * as path from "path";
import os from "os";

// ─── Config ───────────────────────────────────────────────────────────────────

const DRAFTS_DIR = path.join(os.homedir(), ".config", "opencode", "brain", "drafts");

// ─── Style DNA — X voice ────────────────────────────────────────────
// Calm, cinematic, Hinglish, technical but human, builder mindset
// Short punchy lines, no corporate speak, occasional Hindi words
// Hashtags: #buildinpublic #localLLM #AI #OpenCode #100DaysOfCode

const STYLE_GUIDE = `
You are drafting tweets for a B.Tech CSE student.
They build local AI tools, agents, and dev tooling. Their voice on X is:
- all lowercase always. no caps ever except maybe acronyms like AI, LLM, GPU
- tech bro twitter energy but genuine — not cringe hustle bro
- short punchy lines. no commas where a line break works better
- aware of what's trending in AI/dev twitter (agents, local LLMs, vibe coding, MCP, context windows)
- references real tools people use: cursor, claude, opencode, lm studio, ollama
- occasional Hinglish — yaar, bhai, lag gaya, sach mein
- never says "excited to share" or "thrilled to announce" — instant cringe
- no emojis unless 🔥 or 💀 or occasionally 👀
- style inspo: mix of @t3dotgg, @karpathy, @levelsio energy but desi student version

Tone examples:
- "built a memory system for my local ai agent. no cloud. just files + typescript. works perfectly 🔥"
- "yaar local llms have gotten so good. running 35b model on laptop gpu and it's writing better code than me"
- "people sleeping on local inference. ollama + lm studio changed how i work completely"
- "stopped grinding leetcode. started building tools. portfolio > ratings fr"
- "mcp is lowkey the most underrated thing in ai rn. agents that actually remember stuff 👀"

Always generate:
1. A single tweet (under 280 chars)
2. A thread version (3-5 tweets, each under 280 chars)
3. A one-line hook variant (ultra punchy, for max engagement)

Format your response EXACTLY as valid JSON like this:
{
  "single_tweet": "tweet text here",
  "hook": "ultra punchy one liner",
  "thread": [
    "1/ first tweet",
    "2/ second tweet",
    "3/ third tweet"
  ],
  "hashtags": ["#buildinpublic", "#localLLM"],
  "suggested_time": "evening (7-9pm IST) — best engagement window"
}
Return ONLY the JSON. No explanation, no markdown, no preamble.
`;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getTodayDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function getClockTime(): string {
  return new Date().toLocaleTimeString("en-US", {
    hour12: false,
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 40);
}

function ensureDraftsDir(): void {
  if (!fs.existsSync(DRAFTS_DIR)) {
    fs.mkdirSync(DRAFTS_DIR, { recursive: true });
  }
}

function buildDraftFilename(date: string, topic: string): string {
  return path.join(DRAFTS_DIR, `${date}-${slugify(topic)}.md`);
}

function buildDraftMarkdown(params: {
  topic: string;
  context: string;
  single_tweet: string;
  hook: string;
  thread: string[];
  hashtags: string[];
  suggested_time: string;
  date: string;
  time: string;
}): string {
  const threadFormatted = params.thread
    .map((t, i) => `**${i + 1}/** ${t}`)
    .join("\n\n");

  const tagsLine = params.hashtags.join(" ");

  return `# 🐦 Tweet Draft — ${params.date}

> Generated at ${params.time} | Topic: ${params.topic}

---

## 📌 Context
${params.context}

---

## ⚡ Hook (Ultra Punchy)
${params.hook}

---

## 🐦 Single Tweet
${params.single_tweet}

${tagsLine}

---

## 🧵 Thread Version
${threadFormatted}

${tagsLine}

---

## 🕐 Best Time to Post
${params.suggested_time}

---

## 📊 Status
- [ ] Draft
- [ ] Edited
- [ ] Posted

---
*Draft auto-generated by x-draft tool. Edit before posting.*
`;
}

function listDraftFiles(): Array<{ filename: string; date: string; topic: string; status: string }> {
  ensureDraftsDir();
  const files = fs.readdirSync(DRAFTS_DIR).filter(f => f.endsWith(".md"));
  return files.map(filename => {
    const filepath = path.join(DRAFTS_DIR, filename);
    const content = fs.readFileSync(filepath, "utf8");

    // Extract date and topic from filename: YYYY-MM-DD-topic-slug.md
    const match = filename.match(/^(\d{4}-\d{2}-\d{2})-(.+)\.md$/);
    const date = match ? match[1] : "unknown";
    const topicSlug = match ? match[2].replace(/-/g, " ") : filename;

    // Detect status from checkboxes
    let status = "draft";
    if (content.includes("- [x] Posted")) status = "posted";
    else if (content.includes("- [x] Edited")) status = "edited";

    return { filename, date, topic: topicSlug, status };
  });
}

function markDraftPosted(filename: string): string {
  const filepath = path.join(DRAFTS_DIR, filename);
  if (!fs.existsSync(filepath)) return `Error: ${filename} not found.`;

  let content = fs.readFileSync(filepath, "utf8");
  content = content
    .replace("- [ ] Posted", "- [x] Posted")
    .replace("- [ ] Edited", "- [x] Edited");

  // Add posted timestamp
  content = content.replace(
    "*Draft auto-generated by x-draft tool. Edit before posting.*",
    `*Draft auto-generated by x-draft tool.*\n*Posted on: ${getTodayDate()} at ${getClockTime()}*`
  );

  fs.writeFileSync(filepath, content, "utf8");
  return `Marked ${filename} as posted.`;
}

function deleteDraft(filename: string): string {
  const filepath = path.join(DRAFTS_DIR, filename);
  if (!fs.existsSync(filepath)) return `Error: ${filename} not found.`;
  fs.unlinkSync(filepath);
  return `Deleted draft: ${filename}`;
}

function readDraft(filename: string): string {
  const filepath = path.join(DRAFTS_DIR, filename);
  if (!fs.existsSync(filepath)) return `Error: ${filename} not found.`;
  return fs.readFileSync(filepath, "utf8");
}

// ─── LM Studio API call (local inference) ─────────────────────────────────────

async function generateWithLocalLLM(topic: string, context: string): Promise<{
  single_tweet: string;
  hook: string;
  thread: string[];
  hashtags: string[];
  suggested_time: string;
} | null> {
  try {
    const prompt = `${STYLE_GUIDE}\n\nTopic: ${topic}\nContext: ${context}\n\nGenerate the tweet drafts now:`;

    const response = await fetch("http://localhost:1234/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "local-model",
        messages: [{ role: "user", content: prompt }],
        temperature: 0.8,
        max_tokens: 800,
      }),
      signal: AbortSignal.timeout(30000),
    });

    if (!response.ok) return null;

    const data = await response.json() as any;
    const text = data?.choices?.[0]?.message?.content ?? "";

    // Strip markdown fences if present
    const clean = text.replace(/```json|```/g, "").trim();
    return JSON.parse(clean);
  } catch {
    return null;
  }
}

// ─── Tool Definition ──────────────────────────────────────────────────────────

export default tool({
  description:
    "Smart tweet/thread draft generator for @Banshal_Yadav. Generates Hinglish, calm, cinematic X drafts from milestones or topics. Saves drafts to brain/drafts/. Use after completing a milestone (Iron Rule suggestion), or on demand. Supports create, list, read, mark-posted, delete actions.",
  args: {
    action: tool.schema
      .enum(["create", "list", "read", "mark-posted", "delete"])
      .default("create")
      .describe(
        "'create' = generate new draft. 'list' = show all drafts with status. 'read' = view a specific draft. 'mark-posted' = mark draft as posted on X. 'delete' = remove a draft."
      ),
    topic: tool.schema
      .string()
      .optional()
      .describe("What the tweet is about. E.g. 'PDF Suite tool I built today'. Required for create."),
    context: tool.schema
      .string()
      .optional()
      .describe("More detail about the achievement or idea. The more context, the better the draft. Required for create."),
    filename: tool.schema
      .string()
      .optional()
      .describe("Draft filename for read/mark-posted/delete. Get from list action."),
  },

  async execute(args) {
    ensureDraftsDir();

    // ── LIST ──────────────────────────────────────────────────────────────────
    if (args.action === "list") {
      const drafts = listDraftFiles();
      if (drafts.length === 0) return "No drafts yet. Use action=create to generate one.";

      const lines = drafts.map((d, i) =>
        `${i + 1}. [${d.status.toUpperCase()}] ${d.date} — ${d.topic}\n   File: ${d.filename}`
      );
      return `Tweet Drafts (${drafts.length}):\n\n${lines.join("\n\n")}`;
    }

    // ── READ ──────────────────────────────────────────────────────────────────
    if (args.action === "read") {
      if (!args.filename) return "Error: filename required. Use list to get filenames.";
      return readDraft(args.filename);
    }

    // ── MARK POSTED ───────────────────────────────────────────────────────────
    if (args.action === "mark-posted") {
      if (!args.filename) return "Error: filename required. Use list to get filenames.";
      return markDraftPosted(args.filename);
    }

    // ── DELETE ────────────────────────────────────────────────────────────────
    if (args.action === "delete") {
      if (!args.filename) return "Error: filename required. Use list to get filenames.";
      return deleteDraft(args.filename);
    }

    // ── CREATE ────────────────────────────────────────────────────────────────
    if (args.action === "create") {
      if (!args.topic || args.topic.trim().length === 0) {
        return "Error: topic is required for create.";
      }

      const topic = args.topic.trim();
      const context = args.context?.trim() || `Achievement: ${topic}`;
      const date = getTodayDate();
      const time = getClockTime();

      // Try local LLM first
      let generated = await generateWithLocalLLM(topic, context);

      // Fallback — deterministic template if LLM unavailable
      if (!generated) {
        generated = {
          single_tweet: `just built: ${topic}. shipped it. works. 🔥`,
          hook: `built ${topic} from scratch.`,
          thread: [
            `1/ built ${topic} today.`,
            `2/ here's what it does: ${context.slice(0, 200)}`,
            `3/ shipping > perfecting. it works, it's out. what's next?`,
          ],
          hashtags: ["#buildinpublic", "#localLLM", "#AI", "#OpenCode"],
          suggested_time: "evening (7-9pm IST) — best engagement window",
        };
      }

      // Build and save draft file
      const draftContent = buildDraftMarkdown({
        topic,
        context,
        single_tweet: generated.single_tweet,
        hook: generated.hook,
        thread: generated.thread,
        hashtags: generated.hashtags,
        suggested_time: generated.suggested_time,
        date,
        time,
      });

      const filename = buildDraftFilename(date, topic);
      fs.writeFileSync(filename, draftContent, "utf8");

      // Return formatted preview
      const tagsLine = generated.hashtags.join(" ");
      return `
✅ Draft saved: ${path.basename(filename)}

⚡ Hook:
${generated.hook}

🐦 Single Tweet:
${generated.single_tweet}
${tagsLine}

🧵 Thread:
${generated.thread.map((t, i) => `${i + 1}/ ${t}`).join("\n")}
${tagsLine}

🕐 Best time: ${generated.suggested_time}

---
Say "mark this as posted" after you post it, or "show my drafts" to review later.
`.trim();
    }

    return "Invalid action.";
  },
});